version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: f748d7d0e6bd74a6570231c05bb23e9ea420f020
      POSTGRES_DB: postgres_db
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
